answer_format: For each question present the reasoning followed by the correct answer.
base_instruction: Lets think step by step.
few_shot_count: 5
generate_expert_identity: true
generate_intent_keywords: false
generate_reasoning: true
max_eval_batches: 6
min_correct_count: 3
mutate_refine_iterations: 3
mutation_rounds: 2
num_train_examples: 20
prompt_technique_name: critique_n_refine
questions_batch_size: 1
refine_instruction: true
refine_task_eg_iterations: 3
seen_set_size: 20
style_variation: 5
task_description: "Optimize the prompt for clarity and relevance.\nQuestion: What\
  \ is Northwind Health Plus?\nContent: Assistant helps the company employees with\
  \ their healthcare plan questions, and questions about the employee handbook. Be\
  \ brief in your answers.\n        Answer ONLY with the facts listed in the list\
  \ of sources below. If there isnt enough information below, say you dont know. Do\
  \ not generate answers that dont use the sources below. If asking a clarifying question\
  \ to the user would help, ask the question.\n        For tabular information return\
  \ it as an html table. Do not return markdown format. If the question is not in\
  \ English, answer in the language used in the question.\n        Each source has\
  \ a name followed by colon and the actual information, always include the source\
  \ name for each fact you use in the response. Use square brackets to reference the\
  \ source, for example info1.txt. Dont combine sources, list each source separately,\
  \ for example info1.txtinfo2.pdf.\n        \n        \n        \n\nUser How did\
  \ crypto do last year?\nBot Summarize Cryptocurrency Market Dynamics from last year\n\
  User What are my health plans?\nBot Show available health plans\nNorthwind_Standard_Benefits_Details.pdfpage1\
  \ Contoso Electronics Northwind Health Standard Plan Contoso ElectronicsThis document\
  \ contains information generated using a language model Azure OpenAI. The information\
  \ contained in this document is only for demonstration purposes and does not reflect\
  \ the opinions or beliefs of Microsoft. Microsoft makes no representations or warranties\
  \ of any kind, express or implied, about the completeness, accuracy, reliability,\
  \ suitability or availability with respect to the information contained in this\
  \ document. All rights reserved to MicrosoftSummary of Benefits Northwind Standard\
  \ Northwind Standard is a basic plan that provides coverage for medical, vision,\
  \ and dental services. This plan also offers coverage for preventive care services,\
  \ as well as prescription drug coverage. With Northwind Standard, you can choose\
  \ from a variety of innetwork providers, including primary care physicians, specialists,\
  \ hospitals, and pharmacies. This plan does not offer coverage for emergency services,\
  \ mental health and substance abuse coverage, or outofnetwork services.\nNorthwind_Standard_Benefits_Details.pdfpage98\
  \  Right To And Payment Of Benefits OTHER INFORMATION ABOUT THIS PLAN Right To And\
  \ Payment Of Benefits The Northwind Standard plan is a comprehensive health plan\
  \ that provides coverage for medical, vision, and dental services. It also includes\
  \ preventive care services and prescription drug coverage. Northwind Standard offers\
  \ a variety of innetwork providers, including primary care physicians, specialists,\
  \ hospitals, and pharmacies.Under this plan, Northwind Health will cover the cost\
  \ of eligible services you receive, as long as you follow certain rules. Some services\
  \ may require preauthorization or be subject to an annual deductible or coinsurance.\
  \ Northwind Health is also responsible for processing and paying claims correctly.\
  \ Right to Benefits You have the right to receive the benefits available under the\
  \ Northwind Standard plan. This includes the right to receive services from any\
  \ innetwork provider, subject to certain rules and regulations. You also have the\
  \ right to be informed about the types of services that are covered and the costs\
  \ associated with them. Payment of Benefits Northwind Health is responsible for\
  \ paying claims correctly.\nNorthwind_Standard_Benefits_Details.pdfpage35  You should\
  \ also be sure to communicate your needs to the therapist and discuss any potential\
  \ risks or side effects. In addition to massage therapy, Northwind Health also offers\
  \ coverage for other types of physical therapy, such as chiropractic care, physical\
  \ therapy, and occupational therapy. These services can be used to help with pain\
  \ relief, improve mobility, and reduce stress. At Contoso, we want our employees\
  \ to take the time to care for their physical and mental health. We are proud to\
  \ offer coverage for massage therapy and other physical therapy services through\
  \ Northwind Health. With this coverage, you can get the care you need to feel your\
  \ best.Mastectomy and Breast Reconstruction Maternity Care COVERED SERVICES Maternity\
  \ Care At Northwind Health, we understand that having a baby can be costly and stressful.\
  \ To help ease the burden, Northwind Standard offers comprehensive maternity care\
  \ coverage. Prenatal Care Northwind Standard covers the costs of prenatal care for\
  \ the mother, including routine visits with a doctor, laboratory tests, and ultrasounds.\n\
  \nUser What is Northwind Health Plus?\nBot"
top_n: 1
unique_model_id: gpt-4o
