answer_format: For each question present the reasoning followed by the correct answer.
base_instruction: Lets think step by step.
few_shot_count: 5
generate_expert_identity: true
generate_intent_keywords: false
generate_reasoning: true
max_eval_batches: 6
min_correct_count: 3
mutate_refine_iterations: 3
mutation_rounds: 2
num_train_examples: 20
prompt_technique_name: critique_n_refine
questions_batch_size: 1
refine_instruction: true
refine_task_eg_iterations: 3
seen_set_size: 20
style_variation: 5
task_description: "Optimize the prompt for clarity and relevance.\nQuestion: Can you\
  \ give me more details about it ?\nContent: Assistant helps the company employees\
  \ with their healthcare plan questions, and questions about the employee handbook.\
  \ Be brief in your answers.\n        Answer ONLY with the facts listed in the list\
  \ of sources below. If there isnt enough information below, say you dont know. Do\
  \ not generate answers that dont use the sources below. If asking a clarifying question\
  \ to the user would help, ask the question.\n        For tabular information return\
  \ it as an html table. Do not return markdown format. If the question is not in\
  \ English, answer in the language used in the question.\n        Each source has\
  \ a name followed by colon and the actual information, always include the source\
  \ name for each fact you use in the response. Use square brackets to reference the\
  \ source, for example info1.txt. Dont combine sources, list each source separately,\
  \ for example info1.txtinfo2.pdf.\n        \n        \n        \n\nNorthwind_Standard_Benefits_Details.pdfpage44\
  \  If you have questions about coverage or are considering this type of surgery,\
  \ it is important to contact your primary care physician or specialist. You can\
  \ also contact Northwind Standard for more information about coverage and eligibility.\
  \ Prescription Drug COVERED SERVICES Prescription Drugs The Northwind Standard plan\
  \ provides coverage for prescription drugs. This includes both brand name and generic\
  \ medications, as well as overthecounter drugs when prescribed by a doctor. Northwind\
  \ Standard also provides coverage for immunizations and vaccinations. In order to\
  \ receive coverage for prescription drugs, members must use one of Northwind Healths\
  \ preferred pharmacies. Preferred pharmacies offer the lowest copayments, and they\
  \ also provide additional cost savings benefits. To find a preferred pharmacy in\
  \ your area, you can use the Find a Pharmacy tool on the Northwind Health website.\
  \ When filling a prescription, you can choose to receive your medications through\
  \ the mail. This option is convenient and can help you save money. You can also\
  \ request prescription refills online or by phone, and you can even use a mobile\
  \ app to manage your prescriptions.\nNorthwind_Standard_Benefits_Details.pdfpage23\
  \  Clinical trials are research studies that look at new ways to prevent, detect,\
  \ or treat diseases and conditions, and can give members access to treatments and\
  \ therapies not yet available. Northwind Standard offers coverage for certain clinical\
  \ trial services, including those related to common diseases and conditions. The\
  \ Northwind Standard plan covers the cost of certain clinical trial services, and\
  \ some of the most common include  Diagnostic testing and procedures to confirm\
  \ or diagnose a condition or disease  Treatment of the condition or disease being\
  \ studied  Medications  Lab services  Imaging services Any other clinical trial\
  \ services that are not explicitly covered by the Northwind Standard plan may be\
  \ eligible for coverage on a casebycase basis. To determine if a clinical trial\
  \ service is covered, members should contact the Northwind Health customer service\
  \ department for more information.Its important for members to note that the Northwind\
  \ Standard plan does not cover travel expenses associated with attending clinical\
  \ trials.\nNorthwind_Standard_Benefits_Details.pdfpage43  It is also a good idea\
  \ to research the credentials of the surgeon you are considering, as well as the\
  \ hospital or facility where the procedure will be performed.In addition, it is\
  \ important to remember that recovery from orthognathic surgery may take several\
  \ months, and you may need to take time off from work to heal. It is also important\
  \ to note that some patients may experience pain, swelling, and discomfort during\
  \ the recovery period. Finally, it is important to remember that orthognathic surgery\
  \ is a major medical procedure, and it is important to be aware of the risks and\
  \ potential complications. It is also important to discuss any concerns with your\
  \ primary care physician or specialist before making a decision. Northwind Standard\
  \ is committed to providing patients with quality care and coverage for orthognathic\
  \ surgery. If you have questions about coverage or are considering this type of\
  \ surgery, it is important to contact your primary care physician or specialist.\
  \ You can also contact Northwind Standard for more information about coverage and\
  \ eligibility."
top_n: 1
unique_model_id: gpt-4o
